@startuml maskup_general
participant Mask
participant Smartphone
participant Server
participant API
participant "Database" as DB

Smartphone -> Mask: Bluetooth connection request
activate Mask
Mask -> Smartphone: Bluetooth connection confirmation
Smartphone -> API: Connection request
activate API
API -> Server: Server + DB Request
activate Server
Server -> DB: I/O Request
activate DB
DB --> Server: DB response
Server --> API: Server response
deactivate DB
deactivate Server
API --> Smartphone: API Response
deactivate API
Smartphone -> Mask: Components Control
activate Mask
Mask --> Smartphone: Execution confirmation
deactivate Mask
@enduml