@startuml
package "Components" {
    interface IComponent {
        +run()
        +stop()

        +m_state : Enum
    }

    class Vibrator {
        +run()
        +stop()

        +m_state : Enum
    }

    class EmergencyButton {
        +run()
        +stop()

        +m_state : Enum
    }

    class BCHeadPhone {
        +run()
        +stop()

        +m_state : Enum
    }

    class Servomotor {
        +changePosition(inPosition: Position)

        +m_position : Position
        +m_state : Enum
    }

    class ESP_32 {

        +m_pLeftBCHeadPhone : BCHeadPhone
        +m_pRightBCHeadPhone : BCHeadPhone

        +m_pLeftVibrator : Vibrator
        +m_pRightVibrator : Vibrator

        +m_pServomotor : Servomotor
        +m_pEmergencyButton : EmergencyButton
        +m_state : Enum
    }

    enum Position
    {
        Altitude_1000m,
        Altitude_2000m,
        Altitude_3000m,
        Altitude_4000m,
        Altitude_5000m
    }
    
}

package "State Machine" {
    class StateMachine {
        +m_pEsp : ESP_32

        +m_pLeftBCHeadPhone : BCHeadPhone
        +m_pRightBCHeadPhone : BCHeadPhone

        +m_pLeftVibrator : Vibrator
        +m_pRightVibrator : Vibrator

        +m_pServomotor : Servomotor
    }

}

package "FileReader" {
    class JsonFileReader {
        +load()
    }
}

package "Main" {
    class Main {
        +main()
    }
}

EmergencyButton --|> IComponent
Vibrator --|> IComponent
BCHeadPhone --|> IComponent

ESP_32 *--> BCHeadPhone
ESP_32 *--> EmergencyButton
ESP_32 *--> Vibrator
ESP_32 *--> Servomotor
@enduml