name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install json-to-plantuml
        run: npm install -g json-to-plantuml

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Display Files
        run: ls -R $GITHUB_WORKSPACE  # Affichez le contenu du répertoire de travail

      - name: Generate umlpng
        run: |
          for i in ../../*.json; do
            json-to-plantuml -f $i | java -jar $GITHUB_WORKSPACE/Models/plantuml.jar -pipe > $GITHUB_WORKSPACE/$(basename ${i%.json}).png
          done
